version: '3.7'
services:
  db: 
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'your_new_password'
      MYSQL_DATABASE: docker/jwt_authentication/db.sqlite3
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'your_new_password'
    ports:
        - "3307:3307"  
  app: 
      build: ./
      volumes: 
        - .:/docker/jwt_authentication
      ports: 
        - "4000:3000"
      depends_on:
        - db
      links:
        - db
      environment:
        DATABASE_URL: sqlite3:/docker/jwt_authentication/db.sqlite3
